project:
  name: staging-apps
  cluster: staging-cluster
  env: staging

repo:
  url: https://github.com/ramank775/gitops-poc.git
  branch: staging

apps:
  - name: web
    enabled: true
    chart: web
    config: web.yaml
  - name: backend
    enabled: true
    chart: backend
    config: backend.yaml
