apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    description: "This project contains applications for the {{ .Values.project.name }} environment"
    sourceNamespaces:
      - {{ .Values.project.namespace }}
    sourceRepos:
      - {{ .Values.repo.url }}
    destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc 
    orphanedResources: 
      warn: true
    