apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project.name }}
  namespace: argocd #{{ .Values.project.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "This project contains applications for the {{ .Values.project.name }} environment"
  sourceNamespaces:
    - "*"
  sourceRepos:
    - {{ .Values.repo.url }}
  destinations:
    - server: https://kubernetes.default.svc 
      namespace: "*"
    - server: {{ .Values.project.cluster }}
      namespace: "*"
  orphanedResources: 
    warn: false
  clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'