{{- range $instance := .Values.enviroments -}}
{{- if $instance.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $instance.name }}-enviroment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: {{ $.Values.repoURL }}
      path: charts/argocd-apps
      targetRevision: {{ $instance.targetRevision }}
      helm:
        valueFiles:
          - $values/enviroments/{{ $instance.env }}/services/values.yaml
        valueObject:
          project:
            name: {{ $instance.name }}
            namespace: {{ $instance.namespace }}
            cluster: {{ $instance.cluster }}
            env: {{ $instance.env }}

    - repoURL: {{ $.Values.repoURL }}
      targetRevision: {{ $instance.targetRevision }}
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $instance.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: {{ $instance.name }}
    syncOptions:
      - CreateNamespace=true
    
---
{{- end -}}
{{- end -}}